language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++
  - export PACKAGENAME="examol"
  - export ORGNAME="omnia"

script:
  - conda config --add channels https://conda.binstar.org/${ORGNAME}
  - conda build devtools/conda-recipe
  # Install the package
  - conda install --yes --quiet --use-local ${PACKAGENAME}-dev
  # Test the package
  - conda install --yes --quiet nose nose-timer
  - cd /home; nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.3  CONDA_PY=33
    - python=3.4  CONDA_PY=34

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    secure: "jLWBxAqN+oEgaBLw8l4Bj59MWqVePaHMOeDAJAAOLUhbBdS+X0WyCBrEnci0E7CENw/aCbi2vIL4Pl5uxqZvvPD3rKpWefxQB4ePIMsCz2LuOmhIvaUXFeBmjAgQmn/QgDu/5eTveAIBWtkUzR57Rccx0tjBRi3XWOMEpbV8CJQ="

after_success:
  - echo "after_success"
  - ./devtools/travis-ci/after_success.sh
