package:
  name: examol-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm >=6.3
    - numpy
    - scipy
    - scikit-learn
    - lxml

  run:
    - python
    - openmm >=6.3
    - numpy
    - scipy
    - scikit-learn
    - lxml

test:
  requires:
    - nose
  imports:
    - examol

about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
